version: "3.9"
services:
  backend:
    build: ./backend
    container_name: yourfirstcim_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: yourfirstcim_frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./frontend/static/:/usr/share/nginx/html/
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/certs/:/etc/nginx/ssl/
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
