version: "3.9"
services:
  backend:
    build: ./backend
    container_name: yourfirstcim_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
    networks:
      - app_network
    depends_on:
      - redis

  frontend:
    build: ./frontend
    container_name: yourfirstcim_frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - redis
    volumes:
      - ./frontend/static/:/usr/share/nginx/html/
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/certs/:/etc/nginx/ssl/
    networks:
      - app_network

  redis:
    image: redis:7.0-alpine
    container_name: yourfirstcim_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network
    command: redis-server --appendonly yes

networks:
  app_network:
    driver: bridge

volumes:
  redis_data:
